_extends: gh-config

repository:
  description: A python client for the Etcd v2 API https://github.com/coreos/etcd
               It works with the etcd server version 2.3.x to 3.5.x.
  homepage: https://blog.openacid.com
  topics: python, etcd
